# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.10.8753.32995'
- task: UiPathPack@4
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: 'project.json'
    outputType: 'Process'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Test-Personal-Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Shared'
    traceLevel: 'Verbose'

